//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.adpdigital.com/services/messaging", ConfigurationName="ServiceReference1.JaxRpcMessagingService")]
    public interface JaxRpcMessagingService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.sendMultipleResponse sendMultiple(ServiceReference1.sendMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.sendMultipleResponse> sendMultipleAsync(ServiceReference1.sendMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.getBalanceResponse getBalance(ServiceReference1.getBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getBalanceResponse> getBalanceAsync(ServiceReference1.getBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.changePasswordResponse changePassword(ServiceReference1.changePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.changePasswordResponse> changePasswordAsync(ServiceReference1.changePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.getStatusResponse getStatus(ServiceReference1.getStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getStatusResponse> getStatusAsync(ServiceReference1.getStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.receiveResponse receive(ServiceReference1.receiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.receiveResponse> receiveAsync(ServiceReference1.receiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.receiveResponse receive2(ServiceReference1.receiveRequest2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.receiveResponse> receive2Async(ServiceReference1.receiveRequest2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.sendResponse send(ServiceReference1.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.sendResponse> sendAsync(ServiceReference1.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.reportResponse report(ServiceReference1.reportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.reportResponse> reportAsync(ServiceReference1.reportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        ServiceReference1.statusReportResponse statusReport(ServiceReference1.statusReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.statusReportResponse> statusReportAsync(ServiceReference1.statusReportRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class MultiAddressMessageObject
    {
        
        private string contentField;
        
        private short encodingField;
        
        private string[] phoneNumbersField;
        
        private string[] clientIdsField;
        
        private System.DateTime dueTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] phoneNumbers
        {
            get
            {
                return this.phoneNumbersField;
            }
            set
            {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] clientIds
        {
            get
            {
                return this.clientIdsField;
            }
            set
            {
                this.clientIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime dueTime
        {
            get
            {
                return this.dueTimeField;
            }
            set
            {
                this.dueTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class OutgoingMessage
    {
        
        private long idField;
        
        private string clientIdField;
        
        private short statusField;
        
        private string toField;
        
        private System.DateTime timeField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class StatusReport
    {
        
        private long idField;
        
        private short statusField;
        
        private string clientIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class MessageObject
    {
        
        private int chunkField;
        
        private string clientIdField;
        
        private string contentField;
        
        private short encodingField;
        
        private long idField;
        
        private string phoneNumberField;
        
        private short statusField;
        
        private System.Nullable<System.DateTime> timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int chunk
        {
            get
            {
                return this.chunkField;
            }
            set
            {
                this.chunkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string clientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class IncomingMessage
    {
        
        private string contentField;
        
        private short encodingField;
        
        private string fromField;
        
        private long idField;
        
        private object requestField;
        
        private short statusField;
        
        private System.Nullable<System.DateTime> timeField;
        
        private string toField;
        
        private short typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public object request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public short type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReportResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusReportResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiveResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BalanceResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public abstract partial class Result
    {
        
        private short statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class ReportResult : Result
    {
        
        private OutgoingMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messages", IsNullable=false)]
        public OutgoingMessage[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class StatusReportResult : Result
    {
        
        private StatusReport[] reportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("report", IsNullable=false)]
        public StatusReport[] report
        {
            get
            {
                return this.reportField;
            }
            set
            {
                this.reportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class ReceiveResult : Result
    {
        
        private IncomingMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messages", IsNullable=false)]
        public IncomingMessage[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class BalanceResult : Result
    {
        
        private long balanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class SendResult : Result
    {
        
        private long[] idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
        public long[] id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMultiple", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public string sourcePort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public string destPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        public short messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=6)]
        public bool longSupported;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute("messages")]
        public ServiceReference1.MultiAddressMessageObject[] messages;
        
        public sendMultipleRequest()
        {
        }
        
        public sendMultipleRequest(string userName, string password, string shortNumber, string sourcePort, string destPort, short messageType, bool longSupported, ServiceReference1.MultiAddressMessageObject[] messages)
        {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.sourcePort = sourcePort;
            this.destPort = destPort;
            this.messageType = messageType;
            this.longSupported = longSupported;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMultipleResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public ServiceReference1.SendResult sendMultipleReturn;
        
        public sendMultipleResponse()
        {
        }
        
        public sendMultipleResponse(ServiceReference1.SendResult sendMultipleReturn)
        {
            this.sendMultipleReturn = sendMultipleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalance", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class getBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public short facilityId;
        
        public getBalanceRequest()
        {
        }
        
        public getBalanceRequest(string userName, string password, short facilityId)
        {
            this.userName = userName;
            this.password = password;
            this.facilityId = facilityId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalanceResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class getBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public ServiceReference1.BalanceResult getBalanceReturn;
        
        public getBalanceResponse()
        {
        }
        
        public getBalanceResponse(ServiceReference1.BalanceResult getBalanceReturn)
        {
            this.getBalanceReturn = getBalanceReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePassword", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class changePasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string currentPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string newPassword;
        
        public changePasswordRequest()
        {
        }
        
        public changePasswordRequest(string userName, string currentPassword, string newPassword)
        {
            this.userName = userName;
            this.currentPassword = currentPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePasswordResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class changePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public short changePasswordReturn;
        
        public changePasswordResponse()
        {
        }
        
        public changePasswordResponse(short changePasswordReturn)
        {
            this.changePasswordReturn = changePasswordReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatus", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class getStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public long messageId;
        
        public getStatusRequest()
        {
        }
        
        public getStatusRequest(long messageId)
        {
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class getStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public short getStatusReturn;
        
        public getStatusResponse()
        {
        }
        
        public getStatusResponse(short getStatusReturn)
        {
            this.getStatusReturn = getStatusReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receive", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class receiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public long start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public int maxSize;
        
        public receiveRequest()
        {
        }
        
        public receiveRequest(string userName, string password, string shortNumber, long start, int maxSize)
        {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.start = start;
            this.maxSize = maxSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class receiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public ServiceReference1.ReceiveResult receiveReturn;
        
        public receiveResponse()
        {
        }
        
        public receiveResponse(ServiceReference1.ReceiveResult receiveReturn)
        {
            this.receiveReturn = receiveReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receive2", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class receiveRequest2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public long start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public int maxSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        public int encoding;
        
        public receiveRequest2()
        {
        }
        
        public receiveRequest2(string userName, string password, string shortNumber, long start, int maxSize, int encoding)
        {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.start = start;
            this.maxSize = maxSize;
            this.encoding = encoding;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string sourceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("destNo")]
        public string[] destNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public string sourcePort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        public string destPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("clientId")]
        public string[] clientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=7)]
        public short messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=8)]
        public short encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=9)]
        public bool longSupported;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=10)]
        public System.DateTime dueTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=11)]
        public string content;
        
        public sendRequest()
        {
        }
        
        public sendRequest(string userName, string password, string sourceNo, string[] destNo, string sourcePort, string destPort, string[] clientId, short messageType, short encoding, bool longSupported, System.DateTime dueTime, string content)
        {
            this.userName = userName;
            this.password = password;
            this.sourceNo = sourceNo;
            this.destNo = destNo;
            this.sourcePort = sourcePort;
            this.destPort = destPort;
            this.clientId = clientId;
            this.messageType = messageType;
            this.encoding = encoding;
            this.longSupported = longSupported;
            this.dueTime = dueTime;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public ServiceReference1.SendResult sendReturn;
        
        public sendResponse()
        {
        }
        
        public sendResponse(ServiceReference1.SendResult sendReturn)
        {
            this.sendReturn = sendReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="report", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class reportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public string fromClientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public string clientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        public string fromId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=6)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=7)]
        public int maxSize;
        
        public reportRequest()
        {
        }
        
        public reportRequest(string userName, string password, string shortNumber, string fromClientId, string clientId, string fromId, string id, int maxSize)
        {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.fromClientId = fromClientId;
            this.clientId = clientId;
            this.fromId = fromId;
            this.id = id;
            this.maxSize = maxSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reportResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class reportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public ServiceReference1.ReportResult reportReturn;
        
        public reportResponse()
        {
        }
        
        public reportResponse(ServiceReference1.ReportResult reportReturn)
        {
            this.reportReturn = reportReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="statusReport", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class statusReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("clientIds")]
        public string[] clientIds;
        
        public statusReportRequest()
        {
        }
        
        public statusReportRequest(string userName, string password, string shortNumber, string type, long[] ids, string[] clientIds)
        {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.type = type;
            this.ids = ids;
            this.clientIds = clientIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="statusReportResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class statusReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public ServiceReference1.StatusReportResult statusReportReturn;
        
        public statusReportResponse()
        {
        }
        
        public statusReportResponse(ServiceReference1.StatusReportResult statusReportReturn)
        {
            this.statusReportReturn = statusReportReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface JaxRpcMessagingServiceChannel : ServiceReference1.JaxRpcMessagingService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class JaxRpcMessagingServiceClient : System.ServiceModel.ClientBase<ServiceReference1.JaxRpcMessagingService>, ServiceReference1.JaxRpcMessagingService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JaxRpcMessagingServiceClient() : 
                base(JaxRpcMessagingServiceClient.GetDefaultBinding(), JaxRpcMessagingServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MessagingService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaxRpcMessagingServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(JaxRpcMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), JaxRpcMessagingServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaxRpcMessagingServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JaxRpcMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaxRpcMessagingServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JaxRpcMessagingServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaxRpcMessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.sendMultipleResponse sendMultiple(ServiceReference1.sendMultipleRequest request)
        {
            return base.Channel.sendMultiple(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendMultipleResponse> sendMultipleAsync(ServiceReference1.sendMultipleRequest request)
        {
            return base.Channel.sendMultipleAsync(request);
        }
        
        public ServiceReference1.getBalanceResponse getBalance(ServiceReference1.getBalanceRequest request)
        {
            return base.Channel.getBalance(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getBalanceResponse> getBalanceAsync(ServiceReference1.getBalanceRequest request)
        {
            return base.Channel.getBalanceAsync(request);
        }
        
        public ServiceReference1.changePasswordResponse changePassword(ServiceReference1.changePasswordRequest request)
        {
            return base.Channel.changePassword(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.changePasswordResponse> changePasswordAsync(ServiceReference1.changePasswordRequest request)
        {
            return base.Channel.changePasswordAsync(request);
        }
        
        public ServiceReference1.getStatusResponse getStatus(ServiceReference1.getStatusRequest request)
        {
            return base.Channel.getStatus(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getStatusResponse> getStatusAsync(ServiceReference1.getStatusRequest request)
        {
            return base.Channel.getStatusAsync(request);
        }
        
        public ServiceReference1.receiveResponse receive(ServiceReference1.receiveRequest request)
        {
            return base.Channel.receive(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.receiveResponse> receiveAsync(ServiceReference1.receiveRequest request)
        {
            return base.Channel.receiveAsync(request);
        }
        
        public ServiceReference1.receiveResponse receive2(ServiceReference1.receiveRequest2 request)
        {
            return base.Channel.receive2(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.receiveResponse> receive2Async(ServiceReference1.receiveRequest2 request)
        {
            return base.Channel.receive2Async(request);
        }
        
        public ServiceReference1.sendResponse send(ServiceReference1.sendRequest request)
        {
            return base.Channel.send(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendResponse> sendAsync(ServiceReference1.sendRequest request)
        {
            return base.Channel.sendAsync(request);
        }
        
        public ServiceReference1.reportResponse report(ServiceReference1.reportRequest request)
        {
            return base.Channel.report(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.reportResponse> reportAsync(ServiceReference1.reportRequest request)
        {
            return base.Channel.reportAsync(request);
        }
        
        public ServiceReference1.statusReportResponse statusReport(ServiceReference1.statusReportRequest request)
        {
            return base.Channel.statusReport(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.statusReportResponse> statusReportAsync(ServiceReference1.statusReportRequest request)
        {
            return base.Channel.statusReportAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessagingService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessagingService))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.adpdigital.com/services/MessagingService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return JaxRpcMessagingServiceClient.GetBindingForEndpoint(EndpointConfiguration.MessagingService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return JaxRpcMessagingServiceClient.GetEndpointAddress(EndpointConfiguration.MessagingService);
        }
        
        public enum EndpointConfiguration
        {
            
            MessagingService,
        }
    }
}
